### ISSUE TITLE
Add a `getByIdsIn` to AbstractService

### ISSUE THREAD

**Issue by johangirod** [Evaneos/berthe#68]
## Problem : 
Sometimes, we want to get ressource by ids. And sometimes, when those ids come from the outside (MongoDB, LocalStorage, whatever), we cannot garanty consistency. This means that sometimes, the ressource associated to one of the ids does not exists anymore.

For now, the default behaviour of getById is to throw an exception.

But what if I still want to have the other ids ? For composition for instance...

Now, I'm obliged to add a method `getByIdsIn` in the service of my ressource. It sucks.

## Solution
What I propose, is to add a `getByIdsIn` in the AbstractService, which doesn't throw an Exception when one of the id is missing.

What do you think ?

**Comment by johangirod** [comment]
Something like this : 
```php
    public function getByIdsIn(array $ids=array())
    {
        $fetcher = new Fetcher(-1,-1);
        $fetcher->filterByIds($ids);
        return $this->getByFetcher($fetcher)->getResultSet();
    }
```

**Comment by remievaneos** [comment]
My question is : why, originally, did we need to throw an exception if not all ids were retrieved?

Is there something that relies on it? Because, frankly, from what I've seen, it was more a problem than a problem solver when that exception is thrown.

**Comment by maffpool** [comment]
Hum
If you do that, you'll need to ensure, in the caller, that Id you asked for was correctly retrieved
Which means code like that :

```php
$myIds = array(1, 2, 3, 4);
$myObjects = $manager->getByIdsIn($myIds);

foreach ($myIds as $id) {
    if (isset($myObjects[$id]) {
        ...
    }
}
``` 
I don't like this, cause I'm sure we'll encounter bad code with `undefined index` one day

Maybe your method getByIdsIn should return the same number of results than you asked ?
```
array(
    1 => Object...,
    2 => null,
    3 => Object...
);
```

But i neither like this :)

**Comment by maffpool** [comment]
In any case, even if it's an example, please avoid this : 

```php
array $ids=array()
```

**Comment by johangirod** [comment]
>In any case, even if it's an example, please avoid this :
> ```php 
array $ids=array()```

Why that ?

>Maybe your method getByIdsIn should return the same number of results than you asked ?

That would be a great solution. Maybe rename the method to `getByIdsWithDefault` ? Or add a boolean to the method signature ? (I think that for the last case some people disagree)

**Comment by oliviermadre** [comment]
Having a new method in the service won't change anything (unless you disable error handler at the beginning of the method and restore it at the end, which would be weird).
The behaviour you're talking about is coming from the DAL, the service and the manager are both doing nothing.

BTW, the AbstractStorage isn't throwing any exception on the getByIds method.
It triggers an E_USER_NOTICE.
Throwing an exception when you simple have a notice is due to your application configuration, fix it instead of adding a method in service+manager+storage.

Moreover, you can't say you want to disable error because your app is, for some reasons, inconsistent.
You have to handle consistency. You don't change your framework because you haven't manage to keep your model consistent.

@remievaneos : 
We're not throwing exception, but, ask yourself this question : You prefer to have strong checks against your model or you prefer a lax framework ? I remember when we've added the E_USER_NOTICE : I've asked people, they've all agreed on that point.

**Comment by johangirod** [comment]
Okay. Seems legit, again a problem with the conf in API. I just wonder who had the idea to throw an error for each user notice.

**Comment by maffpool** [comment]
> array $ids=array()
> Why that ?

Adding a default value to your parameter means you want to call it without parameter :
```
$result = $manager->getByIdsIn();
```

Makes non sense

**Comment by johangirod** [comment]
Indeed. Thanks for the input!
